// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function CheckIsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(3448338304);
}

export function KillAllTunnels(): $CancellablePromise<string> {
    return $Call.ByID(2040073865);
}

export function RunCommands(cmd: string): $CancellablePromise<string> {
    return $Call.ByID(156145418, cmd);
}

export function RunTunnelCreate(port: string): $CancellablePromise<number> {
    return $Call.ByID(1145039994, port);
}

export function RunTunnelLogin(): $CancellablePromise<string> {
    return $Call.ByID(1041997867);
}

export function RunTunnelLogout(): $CancellablePromise<string> {
    return $Call.ByID(1165502072);
}

export function StopAnyPID(pid: number): $CancellablePromise<boolean> {
    return $Call.ByID(3286370596, pid);
}
